### ISSUE TITLE
Link to VM is not working

### ISSUE THREAD

**Issue by axoaxel** [hongjun922/CPS_Invariant#1]
Thanks for sharing the artifact from your CCS work. 

I got the following Issue: the link to download the virtual machine listed in the README is not working. After login with Microsoft, I got the error  "User not in directory". I assume that it can be downloaded only by authorized users. 

How can I access the VM?

Thanks

**Comment by hongjun9** [comment]
Thanks for you interests in my research. 

Here is the new link for the VM. 

https://purdue0-my.sharepoint.com/:f:/g/personal/choi293_purdue_edu1/EvVb1vKczzNInUlpg_l3Vb4BZEg2UogOEwSgbuDcDCoqww?e=6Oyde3 <https://purdue0-my.sharepoint.com/:f:/g/personal/choi293_purdue_edu1/EvVb1vKczzNInUlpg_l3Vb4BZEg2UogOEwSgbuDcDCoqww?e=6Oyde3>

Thanks,
Hongjun

**Comment by axoaxel** [comment]
Thanks :-)
